name: andinh
favicon: null
layout_spectrum: 0.14290108904242516
typography_spectrum: 0.48113685846328735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7208638750016689
  lightness: 0.16086744191125035
  saturation: 0.4708456026855856
  rhythmicContrast: 0.29764304659329355
purpose: []
